# Dependency Review workflow
# Scans pull requests for vulnerable dependencies

name: "Dependency Review"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        # Fail the action if there are critical or high vulnerabilities
        fail-on-severity: moderate
        # Allow licenses
        allow-licenses: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, ISC, 0BSD
        # Deny licenses
        deny-licenses: GPL-2.0, GPL-3.0, LGPL-2.0, LGPL-2.1, LGPL-3.0, AGPL-3.0
        # Add comment to PR with results
        comment-summary-in-pr: always
